# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4e4631d6edca558b3cf63da9659394f3b549076a1241617d4c06628315fe460632b84b63573f8fa3c2a95799039f6a7c7dbeef3993398540dab3e0686f2f5ee9

test:
  secret_key_base: 36e6b0af83d9f34c0f9b080b54a52eae40faf5beced8db65fe286ed476746527b77d086172093d009bd9441b373c09c4df9e3a5f6961ccf76a953de60f11d2ec

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
